
services:
  pgsql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: carcontrol
      POSTGRES_PASSWORD: carcontrol
      POSTGRES_DB: carcontrol
    volumes:
      - pgsqlvolume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadminvolume:/var/lib/pgadmin

volumes:
  pgsqlvolume:
  pgadminvolume: